# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_auto_20170912_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.BigIntegerField(blank=True, default=99, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='otp',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
