# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_auto_20170921_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.BigIntegerField(default=99),
        ),
    ]
